spring.application.name=noteflow-backend
spring.datasource.generate-unique-name=false
spring.datasource.name=notedb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=db

